// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkinAnalysis.Api.Data;

#nullable disable

namespace SkinAnalysis.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409015237_AddMissingScoreColumns")]
    partial class AddMissingScoreColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkinAnalysis.Api.Models.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AcneActive")
                        .HasColumnType("boolean")
                        .HasColumnName("acne_active");

                    b.Property<int>("AcneScore")
                        .HasColumnType("integer")
                        .HasColumnName("acne_score");

                    b.Property<string>("AdditionalRecommendations")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("additional_recommendations");

                    b.Property<int>("Cravos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("DarkCircles")
                        .HasColumnType("boolean")
                        .HasColumnName("dark_circles");

                    b.Property<int>("DarkSpotsScore")
                        .HasColumnType("integer")
                        .HasColumnName("dark_spots_score");

                    b.Property<bool>("DryLips")
                        .HasColumnType("boolean")
                        .HasColumnName("dry_lips");

                    b.Property<bool>("EnlargedPores")
                        .HasColumnType("boolean")
                        .HasColumnName("enlarged_pores");

                    b.Property<int>("EspinhasAtivas")
                        .HasColumnType("integer");

                    b.Property<int>("HydrationScore")
                        .HasColumnType("integer")
                        .HasColumnName("hydration_score");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<int>("LinhasFinas")
                        .HasColumnType("integer");

                    b.Property<int>("OilinessScore")
                        .HasColumnType("integer")
                        .HasColumnName("oiliness_score");

                    b.Property<int>("Olheiras")
                        .HasColumnType("integer");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer")
                        .HasColumnName("overall_score");

                    b.Property<bool>("PigmentationSpots")
                        .HasColumnType("boolean")
                        .HasColumnName("pigmentation_spots");

                    b.Property<int>("Poros")
                        .HasColumnType("integer");

                    b.Property<string>("RoutineJson")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("routine_json");

                    b.Property<int>("SensitivityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sensitivity_score");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skin_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Vermelhidao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("analysis", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string[]>("Actives")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("actives");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string[]>("Concerns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("concerns");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUserProduct")
                        .HasColumnType("boolean")
                        .HasColumnName("is_user_product");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string[]>("Period")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("period");

                    b.Property<decimal?>("PriceAvg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_avg");

                    b.Property<string>("PriceRange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("price_range");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skin_type");

                    b.Property<string[]>("SkinTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skin_types");

                    b.Property<string>("StrengthLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("strength_level");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Actives")
                        .HasDatabaseName("idx_products_actives_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Actives"), "GIN");

                    b.HasIndex("Category");

                    b.HasIndex("Concerns")
                        .HasDatabaseName("idx_products_concerns_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Concerns"), "GIN");

                    b.HasIndex("Period")
                        .HasDatabaseName("idx_products_period_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Period"), "GIN");

                    b.HasIndex("PriceRange");

                    b.HasIndex("SkinTypes")
                        .HasDatabaseName("idx_products_skin_types_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SkinTypes"), "GIN");

                    b.HasIndex("UserId");

                    b.HasIndex("Brand", "Name");

                    b.HasIndex("UserId", "IsUserProduct");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.ProductRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string[]>("Actives")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("actives");

                    b.Property<string[]>("Concerns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("concerns");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string[]>("Periods")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("periods");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Reasoning")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reasoning");

                    b.Property<string[]>("SkinTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skin_types");

                    b.Property<string[]>("StepTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("step_types");

                    b.Property<string>("StrengthLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("strength_level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Concerns")
                        .HasDatabaseName("idx_product_rules_concerns_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Concerns"), "GIN");

                    b.HasIndex("Periods")
                        .HasDatabaseName("idx_product_rules_periods_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Periods"), "GIN");

                    b.HasIndex("Priority");

                    b.HasIndex("ProductId");

                    b.HasIndex("SkinTypes")
                        .HasDatabaseName("idx_product_rules_skin_types_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SkinTypes"), "GIN");

                    b.HasIndex("StepTypes")
                        .HasDatabaseName("idx_product_rules_step_types_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StepTypes"), "GIN");

                    b.ToTable("product_rules", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("product");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.RecommendationCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string[]>("Concerns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("concerns");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("HitCount")
                        .HasColumnType("integer")
                        .HasColumnName("hit_count");

                    b.Property<string[]>("Periods")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("periods");

                    b.Property<string>("RecommendationHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendation_hash");

                    b.Property<Guid[]>("RecommendedProductIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("recommended_product_ids");

                    b.Property<decimal[]>("Scores")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("scores");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skin_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId", "RecommendationHash")
                        .IsUnique();

                    b.ToTable("user_recommendations_cache", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.RecommendationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiEngine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_engine");

                    b.Property<Guid?>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackComment")
                        .HasColumnType("text")
                        .HasColumnName("feedback_comment");

                    b.Property<DateTime?>("FeedbackProvidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("feedback_provided_at");

                    b.Property<int?>("FeedbackRating")
                        .HasColumnType("integer")
                        .HasColumnName("feedback_rating");

                    b.Property<decimal>("HighestScore")
                        .HasColumnType("numeric")
                        .HasColumnName("highest_score");

                    b.Property<string[]>("InputConcerns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("input_concerns");

                    b.Property<string[]>("InputPeriods")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("input_periods");

                    b.Property<string>("InputSkinType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_skin_type");

                    b.Property<int>("RecommendationCount")
                        .HasColumnType("integer")
                        .HasColumnName("recommendation_count");

                    b.Property<decimal[]>("RecommendationScores")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("recommendation_scores");

                    b.Property<Guid[]>("RecommendedProductIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("recommended_product_ids");

                    b.Property<string>("RoutineType")
                        .HasColumnType("text")
                        .HasColumnName("routine_type");

                    b.Property<Guid[]>("SelectedProductIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("selected_product_ids");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("FeedbackProvidedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FeedbackProvidedAt")
                        .IsDescending(false, true);

                    b.ToTable("recommendation_logs", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BasedOnAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("based_on_analysis_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BasedOnAnalysisId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsActive")
                        .IsUnique()
                        .HasFilter("is_active = true");

                    b.ToTable("routine", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.RoutineStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsUserProduct")
                        .HasColumnType("boolean")
                        .HasColumnName("is_user_product");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid")
                        .HasColumnName("routine_id");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("step_type");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RoutineId");

                    b.ToTable("routine_step", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.SkinAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcneLevel")
                        .HasColumnType("integer")
                        .HasColumnName("acne_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasDarkCircles")
                        .HasColumnType("boolean")
                        .HasColumnName("has_dark_circles");

                    b.Property<bool>("HasSpots")
                        .HasColumnType("boolean")
                        .HasColumnName("has_spots");

                    b.Property<int>("SensitivityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("sensitivity_level");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skin_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("skin_analysis", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<string>("CheckoutUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("checkout_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gateway");

                    b.Property<string>("PixQrCode")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("pix_qr_code");

                    b.Property<string>("PixQrCodeBase64")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("pix_qr_code_base64");

                    b.Property<string>("PlanKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_key");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("ExternalReference")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.UserCredit", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("CreditsRemaining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("credits_remaining");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_credits", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.UserProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("custom_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("user_products", (string)null);
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.Product", b =>
                {
                    b.HasOne("SkinAnalysis.Api.Models.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.ProductRule", b =>
                {
                    b.HasOne("SkinAnalysis.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.Recommendation", b =>
                {
                    b.HasOne("SkinAnalysis.Api.Models.Analysis", "Analysis")
                        .WithMany("Recommendations")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.RecommendationCache", b =>
                {
                    b.HasOne("SkinAnalysis.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.RecommendationLog", b =>
                {
                    b.HasOne("SkinAnalysis.Api.Models.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkinAnalysis.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.Routine", b =>
                {
                    b.HasOne("SkinAnalysis.Api.Models.SkinAnalysis", "BasedOnAnalysis")
                        .WithMany("Routines")
                        .HasForeignKey("BasedOnAnalysisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinAnalysis.Api.Models.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasedOnAnalysis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.RoutineStep", b =>
                {
                    b.HasOne("SkinAnalysis.Api.Models.Product", "Product")
                        .WithMany("RoutineSteps")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinAnalysis.Api.Models.Routine", "Routine")
                        .WithMany("Steps")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.SkinAnalysis", b =>
                {
                    b.HasOne("SkinAnalysis.Api.Models.User", "User")
                        .WithMany("SkinAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.UserProduct", b =>
                {
                    b.HasOne("SkinAnalysis.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinAnalysis.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.Analysis", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.Product", b =>
                {
                    b.Navigation("RoutineSteps");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.Routine", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.SkinAnalysis", b =>
                {
                    b.Navigation("Routines");
                });

            modelBuilder.Entity("SkinAnalysis.Api.Models.User", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Routines");

                    b.Navigation("SkinAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
