import type { QuizQuestion } from "./SkinQuiz";
import type { LifestyleAnswers } from "@/components/analyze/LifestyleQuestionnaire";
import {
  faClock, faCircleDot, faStar, faMagnifyingGlass,
  faDroplet, faWind, faBolt, faArrowUp, faBandage, faFire,
  faTag, faShoppingBag, faCrown, faGem,
  faVenus, faMars, faMinus,
  faLeaf, faBan, faShield, faSprayCanSparkles,
  faSun, faCloud, faCloudSun, faMoon,
  faPumpSoap, faBottleWater, faFlask, faSprayCan, faSyringe, faBrush,
  faCheck, faQuestion, faExclamation,
  faHeartCrack, faDna, faPersonPregnant, faVenusMars,
  faSliders, faEquals,
} from "@fortawesome/free-solid-svg-icons";

// ─── Pré-análise: contexto para a IA (enviadas com a foto) ───────────────────
// Ajudam a IA a interpretar a imagem com mais precisão.

export const PRE_ANALYSIS_QUESTIONS: QuizQuestion[] = [
  // Pergunta 1 — contexto demográfico
  {
    id: "ageRange",
    question: "Qual sua faixa etária?",
    highlight: "faixa etária",
    subtitle: "Sua pele muda com o tempo — isso ajuda a indicar os cuidados ideais.",
    mascotMood: "happy",
    type: "single",
    columns: 1,
    options: [
      { id: "under25", label: "Menos de 25 anos" },
      { id: "25to34",  label: "25 a 34 anos"     },
      { id: "35to44",  label: "35 a 44 anos"     },
      { id: "45to60",  label: "45 a 60 anos"     },
      { id: "over60",  label: "Mais de 60 anos"  },
    ],
  },
  // Pergunta 2 — sensibilidade (ajuda a IA calibrar limiares de vermelhidão e irritação)
  {
    id: "skinSensitivity",
    question: "Sua pele costuma reagir a produtos?",
    highlight: "reagir",
    subtitle: "Ajuda a IA a calibrar vermelhidão e sensibilidade na análise.",
    mascotMood: "thinking",
    type: "single",
    columns: 1,
    options: [
      { id: "sensitive",     label: "Sim — arde, fica vermelha ou irrita com facilidade", faIcon: faExclamation },
      { id: "not_sensitive", label: "Não — tolera bem a maioria dos produtos",             faIcon: faCheck       },
      { id: "unsure",        label: "Às vezes — depende do produto",                       faIcon: faQuestion    },
    ],
  },
  // Pergunta 3 — preocupações principais (direciona o foco da IA)
  {
    id: "primaryConcern",
    question: "O que mais te incomoda na pele?",
    highlight: "incomoda",
    subtitle: "Selecione todas que se aplicam.",
    mascotMood: "thinking",
    type: "multi",
    columns: 2,
    options: [
      { id: "rugas",       label: "Rugas e linhas finas",  faIcon: faClock           },
      { id: "acne",        label: "Acne e espinhas",       faIcon: faFire            },
      { id: "manchas",     label: "Manchas",               faIcon: faCircleDot       },
      { id: "poros",       label: "Poros visíveis",        faIcon: faMagnifyingGlass },
      { id: "vermelhidao", label: "Vermelhidão",           faIcon: faBolt            },
      { id: "hidratacao",  label: "Pele ressecada",        faIcon: faDroplet         },
      { id: "textura",     label: "Textura irregular",     faIcon: faSliders         },
      { id: "oleosidade",  label: "Oleosidade excessiva",  faIcon: faSprayCan        },
      { id: "firmeza",     label: "Firmeza / contorno",    faIcon: faArrowUp         },
      { id: "marcas_acne", label: "Marcas pós-acne",       faIcon: faBandage         },
      { id: "descobrir",   label: "Quero descobrir com FaceGlow", faIcon: faStar     },
    ],
  },
];

// ─── Pós-análise: contexto para a rotina (coletadas durante o loading) ────────
// Chegam enquanto a IA processa — sem conflito com a análise.

export const ROUTINE_QUESTIONS: QuizQuestion[] = [
  {
    id: "budgetRange",
    question: "Quanto você costuma investir em skincare?",
    highlight: "investir",
    subtitle: "Sem pressão — a ideia é encontrar o que faz sentido pra você.",
    mascotMood: "happy",
    type: "single",
    columns: 2,
    options: [
      { id: "super_low", label: "Super econômico", sublabel: "Produtos até R$ 50",            faIcon: faTag    },
      { id: "low",       label: "Econômico",       sublabel: "Até R$ 100 por mês",            faIcon: faTag    },
      { id: "medium",    label: "Intermediário",   sublabel: "R$ 100 a R$ 250 por mês",       faIcon: faStar   },
      { id: "high",      label: "Premium",         sublabel: "R$ 250 a R$ 500 por mês",       faIcon: faGem    },
      { id: "premium",   label: "Sem restrição",   sublabel: "O que funcionar para mim!",     faIcon: faCrown  },
    ],
  },
  {
    id: "makeupUsage",
    question: "Você usa maquiagem?",
    subtitle: "Isso define se incluímos limpeza de maquiagem na rotina noturna.",
    mascotMood: "thinking",
    type: "single",
    columns: 2,
    options: [
      { id: "daily",     label: "Sim, diariamente",  faIcon: faBrush            },
      { id: "sometimes", label: "Sim, às vezes",     faIcon: faSprayCanSparkles },
      { id: "rarely",    label: "Raramente",          faIcon: faLeaf             },
      { id: "never",     label: "Não uso maquiagem", faIcon: faBan              },
    ],
  },
  {
    id: "sunscreenUsage",
    question: "Você usa protetor solar?",
    subtitle: "O protetor é o anti-idade mais eficaz que existe.",
    mascotMood: "happy",
    type: "single",
    columns: 2,
    options: [
      { id: "always",    label: "Sempre",     faIcon: faSun      },
      { id: "sometimes", label: "Às vezes",   faIcon: faCloudSun },
      { id: "rarely",    label: "Raramente",  faIcon: faCloud    },
      { id: "never",     label: "Nunca",      faIcon: faMoon     },
    ],
  },
];

// ─── Full (refinamento — 14 perguntas) ───────────────────────────────────────

export const FULL_QUESTIONS: QuizQuestion[] = [
  {
    id: "ageRange",
    question: "Qual sua faixa etária?",
    highlight: "faixa etária",
    subtitle: "Sua pele muda com o tempo — isso ajuda a indicar os cuidados ideais.",
    mascotMood: "happy",
    type: "single",
    columns: 1,
    options: [
      { id: "under25", label: "Menos de 25 anos" },
      { id: "25to34",  label: "25 a 34 anos"     },
      { id: "35to44",  label: "35 a 44 anos"     },
      { id: "45to60",  label: "45 a 60 anos"     },
      { id: "over60",  label: "Mais de 60 anos"  },
    ],
  },
  {
    id: "gender",
    question: "Com qual gênero você se identifica?",
    highlight: "gênero",
    subtitle: "Os hormônios influenciam bastante no comportamento da pele.",
    mascotMood: "happy",
    type: "single",
    columns: 2,
    options: [
      { id: "female",     label: "Feminino",            faIcon: faVenus     },
      { id: "male",       label: "Masculino",           faIcon: faMars      },
      { id: "nonbinary",  label: "Não binário",         faIcon: faVenusMars },
      { id: "prefer_not", label: "Prefiro não informar",faIcon: faMinus     },
    ],
  },
  {
    id: "selfReportedSkinType",
    question: "Como você definiria seu tipo de pele?",
    highlight: "tipo de pele",
    mascotMood: "thinking",
    type: "single",
    columns: 2,
    options: [
      { id: "oleosa", label: "Oleosa",  sublabel: "Brilho excessivo, poros aparentes",  faIcon: faSprayCan },
      { id: "seca",   label: "Seca",   sublabel: "Sensação repuxada, descamação",        faIcon: faWind     },
      { id: "normal", label: "Normal", sublabel: "Equilibrada, sem grandes queixas",     faIcon: faEquals   },
      { id: "mista",  label: "Mista",  sublabel: "Zona T oleosa, bochechas mais secas",  faIcon: faSliders  },
    ],
  },
  {
    id: "skinSensitivity",
    question: "Sua pele costuma ser sensível?",
    highlight: "sensível",
    subtitle: "Alguns produtos causam ardência, vermelhidão ou irritação?",
    mascotMood: "thinking",
    type: "single",
    columns: 1,
    options: [
      { id: "sensitive",     label: "Sim, é sensível",   sublabel: "Reage a muitos produtos",           faIcon: faExclamation },
      { id: "not_sensitive", label: "Não é sensível",    sublabel: "Tolera bem a maioria dos produtos", faIcon: faCheck       },
      { id: "unsure",        label: "Não tenho certeza", sublabel: "Depende do produto ou situação",    faIcon: faQuestion    },
    ],
  },
  {
    id: "primaryConcern",
    question: "O que mais te incomoda na pele?",
    highlight: "incomoda",
    subtitle: "Selecione todas que se aplicam.",
    mascotMood: "thinking",
    type: "multi",
    columns: 2,
    options: [
      { id: "rugas",         label: "Rugas e linhas finas",  faIcon: faClock           },
      { id: "acne",          label: "Acne e espinhas",       faIcon: faFire            },
      { id: "manchas",       label: "Manchas",               faIcon: faCircleDot       },
      { id: "poros",         label: "Poros visíveis",        faIcon: faMagnifyingGlass },
      { id: "vermelhidao",   label: "Vermelhidão",           faIcon: faBolt            },
      { id: "hidratacao",    label: "Pele ressecada",        faIcon: faDroplet         },
      { id: "textura",       label: "Textura irregular",     faIcon: faSliders         },
      { id: "oleosidade",    label: "Oleosidade excessiva",  faIcon: faSprayCan        },
      { id: "firmeza",       label: "Firmeza / contorno",    faIcon: faArrowUp         },
      { id: "marcas_acne",   label: "Marcas pós-acne",       faIcon: faBandage         },
      { id: "sensibilidade", label: "Sensibilidade",         faIcon: faShield          },
    ],
  },
  {
    id: "budgetRange",
    question: "Quanto você costuma investir em skincare?",
    highlight: "investir",
    subtitle: "Sem pressão — a ideia é encontrar o que faz sentido pra você.",
    mascotMood: "happy",
    type: "single",
    columns: 2,
    options: [
      { id: "super_low", label: "Super econômico", sublabel: "Produtos até R$ 50",        faIcon: faTag   },
      { id: "low",       label: "Econômico",       sublabel: "Até R$ 100 por mês",        faIcon: faTag   },
      { id: "medium",    label: "Intermediário",   sublabel: "R$ 100 a R$ 250 por mês",   faIcon: faStar  },
      { id: "high",      label: "Premium",         sublabel: "R$ 250 a R$ 500 por mês",   faIcon: faGem   },
      { id: "premium",   label: "Sem restrição",   sublabel: "O que funcionar para mim!", faIcon: faCrown },
    ],
  },
  {
    id: "makeupUsage",
    question: "Você usa maquiagem?",
    subtitle: "Isso define se incluímos uma etapa de limpeza de maquiagem na rotina noturna.",
    mascotMood: "happy",
    type: "single",
    columns: 2,
    options: [
      { id: "daily",     label: "Sim, diariamente",  faIcon: faBrush            },
      { id: "sometimes", label: "Sim, às vezes",     faIcon: faSprayCanSparkles },
      { id: "rarely",    label: "Raramente",          faIcon: faLeaf             },
      { id: "never",     label: "Não uso maquiagem", faIcon: faBan              },
    ],
  },
  {
    id: "sunscreenUsage",
    question: "Você usa protetor solar?",
    subtitle: "O protetor é o anti-idade mais eficaz que existe.",
    mascotMood: "happy",
    type: "single",
    columns: 2,
    options: [
      { id: "always",    label: "Sempre",     faIcon: faSun      },
      { id: "sometimes", label: "Às vezes",   faIcon: faCloudSun },
      { id: "rarely",    label: "Raramente",  faIcon: faCloud    },
      { id: "never",     label: "Nunca",      faIcon: faMoon     },
    ],
  },
  {
    id: "currentRoutineItems",
    question: "O que você já usa hoje?",
    subtitle: "Pode marcar tudo que já faz parte da sua rotina.",
    mascotMood: "happy",
    type: "multi",
    columns: 2,
    options: [
      { id: "none",           label: "Sem rotina ainda",  faIcon: faBan          },
      { id: "cleanser",       label: "Limpador facial",   faIcon: faPumpSoap     },
      { id: "moisturizer",    label: "Hidratante",        faIcon: faBottleWater  },
      { id: "toner",          label: "Tônico",            faIcon: faFlask        },
      { id: "makeup_remover", label: "Removedor de Maquiagem", sublabel: "Demaquilante ou cleansing oil", faIcon: faLeaf },
      { id: "serum",          label: "Sérum",             faIcon: faSyringe      },
      { id: "sunscreen",      label: "Protetor solar",    faIcon: faSun          },
      { id: "exfoliant",      label: "Esfoliante",        faIcon: faSprayCan     },
    ],
  },
  {
    id: "productPreferences",
    question: "O que é importante nos seus produtos?",
    highlight: "importante",
    subtitle: "Pode selecionar vários.",
    mascotMood: "happy",
    type: "multi",
    columns: 2,
    options: [
      { id: "fragrance_free",  label: "Sem fragrância"        },
      { id: "sulfate_free",    label: "Sem sulfatos"          },
      { id: "alcohol_free",    label: "Sem álcool"            },
      { id: "non_comedogenic", label: "Não comedogênico"      },
      { id: "paraben_free",    label: "Livre de parabenos"    },
      { id: "eo_free",         label: "Sem óleos essenciais"  },
      { id: "none",            label: "Sem preferência"       },
    ],
  },
  {
    id: "certifications",
    question: "Quais selos você valoriza?",
    highlight: "selos",
    subtitle: "Pode marcar mais de um.",
    mascotMood: "happy",
    type: "multi",
    columns: 2,
    options: [
      { id: "vegan",        label: "Vegano"                     },
      { id: "cruelty_free", label: "Livre de crueldade animal"  },
      { id: "clean_beauty", label: "Beleza limpa"               },
      { id: "organic",      label: "Orgânico"                   },
      { id: "derma_tested", label: "Testado dermatologicamente" },
      { id: "none",         label: "Sem preferência"            },
    ],
  },
  {
    id: "skinConditions",
    question: "Você possui alguma condição de pele?",
    highlight: "condição",
    mascotMood: "thinking",
    type: "multi",
    columns: 2,
    options: [
      { id: "rosacea",    label: "Rosácea",      faIcon: faBolt        },
      { id: "dermatitis", label: "Dermatite",    faIcon: faHeartCrack  },
      { id: "eczema",     label: "Eczema",        faIcon: faFire        },
      { id: "psoriasis",  label: "Psoríase",     faIcon: faDna         },
      { id: "atopic",     label: "Pele atópica", faIcon: faShield      },
      { id: "none",       label: "Nenhuma",      faIcon: faCheck       },
    ],
  },
  {
    id: "hormonalConditions",
    question: "Existe algo que possa afetar sua pele?",
    highlight: "afetar",
    subtitle: "Importante para evitar ingredientes contraindicados.",
    mascotMood: "thinking",
    type: "multi",
    columns: 2,
    options: [
      { id: "pregnancy",   label: "Gravidez",               faIcon: faPersonPregnant },
      { id: "breastfeed",  label: "Amamentação",            faIcon: faDroplet        },
      { id: "hormonal",    label: "Desequilíbrio hormonal", faIcon: faSliders        },
      { id: "menopause",   label: "Menopausa",              faIcon: faMoon           },
      { id: "autoimmune",  label: "Doença autoimune",       faIcon: faDna            },
      { id: "none",        label: "Nenhuma",                faIcon: faCheck          },
    ],
  },
  {
    id: "ingredientReactions",
    question: "Já teve reação a algum ingrediente?",
    highlight: "reação",
    subtitle: "Se souber, marque aqui — evitaremos esses ativos.",
    mascotMood: "sad",
    type: "multi",
    columns: 2,
    options: [
      { id: "retinol",     label: "Retinol / Vitamina A"   },
      { id: "niacinamide", label: "Niacinamida"            },
      { id: "vitamin_c",   label: "Vitamina C"             },
      { id: "salicylic",   label: "Ácido salicílico (BHA)" },
      { id: "aha",         label: "Ácidos AHA"             },
      { id: "fragrance",   label: "Fragrâncias"            },
      { id: "alcohol",     label: "Álcool"                 },
      { id: "sulfates",    label: "Sulfatos"               },
      { id: "none",        label: "Nunca percebi",         faIcon: faCheck },
    ],
  },
];

// ─── Conversão: respostas do SkinQuiz → LifestyleAnswers ─────────────────────

export function quizToLifestyle(answers: Record<string, string[]>): LifestyleAnswers {
  const s = (id: string) => answers[id]?.[0] ?? "";
  const m = (id: string) => answers[id] ?? [];

  const concerns = m("primaryConcern");
  return {
    ageRange:              s("ageRange"),
    gender:                s("gender"),
    selfReportedSkinType:  s("selfReportedSkinType"),
    skinSensitivity:       s("skinSensitivity"),
    primaryConcern:        concerns[0] ?? "",
    secondaryConcerns:     concerns.slice(1),
    budgetRange:           s("budgetRange"),
    makeupUsage:           s("makeupUsage"),
    sunscreenUsage:        s("sunscreenUsage"),
    currentRoutineItems:   m("currentRoutineItems"),
    hormonalConditions:    m("hormonalConditions"),
    skinConditions:        m("skinConditions"),
    ingredientReactions:   m("ingredientReactions"),
    productPreferences:    m("productPreferences"),
    certifications:        m("certifications"),
  };
}
